name: blah
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.6
  - netcdf4
  - pytest
  - pytest-benchmark
  - cartopy<0.20
  - pip
  - pip:
    - motuclient
